In [271]:
from regression import add_neighborhood_feature, avg_loss, SGD, sigmoid
import numpy as np
import matplotlib.pyplot as plt
import random
from matplotlib.colors import ListedColormap, BoundaryNorm

In [272]:
# #code to generate data
# def makeTask1Sets(N, dest):
#     matrices = []
#     labels = []
#     for _ in range(int(N)):
#         dgrm = diagram.createDiagram()
#         danger = np.array(dgrm.layWires())
#         matrices.append(dgrm.data.flatten())
#         labels.append(danger)
#     matrices = np.array(matrices)
#     labels = np.array(labels)

#     # In case the necessary directory hasn't been made yet
#     #os.makedirs(dest, exist_ok=True)
#     np.save(arr=matrices,file=f'{dest}/data.npy',allow_pickle=True)
#     np.save(arr=labels,file=f'{dest}/labels.npy',allow_pickle=True)

# def makeTask2Sets(N, dest):
#     matrices = []
#     labels = []

#     count=0
#     while(count<int(N)):
#         dgrm = diagram.createDiagram()
#         wireToCut = np.array((dgrm.layWires())[1])
#         #print(f"my wire to cut: {wireToCut}")
#         if not np.array_equal(wireToCut,(0,0,0,0,1)):
#             matrices.append(dgrm.data.flatten())
#             labels.append(wireToCut)
#             count+=1

#     matrices = np.array(matrices)
#     labels = np.array(labels)

#     # In case the necessary directory hasn't been made yet
#     #os.makedirs(dest, exist_ok=True)
#     np.save(arr=matrices,file=f'{dest}/data.npy',allow_pickle=True)
#     np.save(arr=labels,file=f'{dest}/labels.npy',allow_pickle=True)

[0 0 1 0 0]


In [23]:
"""Load in data: 
    Input Space: (1200, 1) one hot encoded data """

x = np.load('OHE_Task2_Trainset2000\data.npy')[0]
y = np.load('OHE_Task2_Trainset2000\labels.npy')
print(y[0])
w1 = np.random.rand(2000)*2 - np.ones(shape=2000)
w2 = np.random.rand(2000)*2 - np.ones(shape=2000)
w3 = np.random.rand(2000)*2 - np.ones(shape=2000)
w4 = np.random.rand(2000)*2 - np.ones(shape=2000)
w5 = np.random.rand(2000)*2 - np.ones(shape=2000)
weights = np.vstack((w1,w2,w3,w4,w5))


[0 0 1 0 0]


In [273]:
"""Multi-Class Classification Model 
    SoftMax --> computes probabilites for each class totals to 1
    Loss Function --> categorical cross entropy --> for all classes -log(softmax(y'))
    Deriviate of Loss --> y' - y_actual"""

def softmax(output_x=list): # output x takes 4 diff values for each weight layer
    exp_output = np.exp(output_x - np.max(output_x))
    probs = exp_output / np.sum(exp_output, axis=-1, keepdims=True)
    return probs

def cross_entropy_loss(y_true, y_pred):
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    loss = -np.sum(y_true * np.log(y_pred)) / len(y_true)
    return loss

def SGD2(weights, x, ohe_y, alpha):
    logits = []
    for w in weights:
        logits.append(np.dot(w, x))
    y_pred = softmax(logits)
    cur_loss = cross_entropy_loss(ohe_y, y_pred)
    train = alpha * (y_pred - ohe_y)
    for index in range(len(weights)):
        cur_train = train[index]
        cur_weight = weights[index]
        for w in cur_weight:
            w -= cur_train
    logits.clear()
    print(cur_loss)
    return cur_loss


def feed_forward_multiclass(data, labels, num_iters):
    w1 = np.random.rand(2000)*2 - np.ones(shape=2000)
    w2 = np.random.rand(2000)*2 - np.ones(shape=2000)
    w3 = np.random.rand(2000)*2 - np.ones(shape=2000)
    w4 = np.random.rand(2000)*2 - np.ones(shape=2000)
    w5 = np.random.rand(2000)*2 - np.ones(shape=2000)
    weights = np.vstack((w1,w2,w3,w4,w5))
    for i in range(num_iters):
        x = data
        y = labels
        loss = SGD2(weights, x, y, alpha=1)
        print(loss)

# feed_forward_multiclass(x, y, num_iters=10)
logits = []
for w in weights:
    logits.append(np.dot(x, w))
print("logits", logits)

print("softmax logits", softmax(logits))
print("softmax sum", np.sum(softmax(logits)))
print("cur loss", cross_entropy_loss(y, softmax(logits)))
train = 1 * (softmax(logits) - y)
print("training iteration value", (weights[0][0]))
for index in range(len(weights)):
        cur_train = train[index]
        print(cur_train)
        cur_weight = weights[index]
        for w in cur_weight:
            w -= cur_train
print("training iteration value", (weights[0][0]))

logits [-8.006524796055098, -1.8771567204877289, -7.7614315427723, -2.2552027181279053, -1.9327462941367937]
softmax logits [0.00082621 0.37935014 0.00105568 0.25993033 0.35883765]
softmax sum 1.0
cur loss 4.065531381078727
training iteration value 0.8622304612450216
[ 2.47862467e-03  1.13805041e+00 -2.99683296e+00  7.79790984e-01
  1.07651294e+00]
[ 2.47862467e-03  1.13805041e+00 -2.99683296e+00  7.79790984e-01
  1.07651294e+00]
[-2.99752138  1.13805041  0.00316704  0.77979098  1.07651294]
[-2.99752138  1.13805041  0.00316704  0.77979098  1.07651294]
[ 0.00247862  1.13805041  0.00316704 -2.22020902  1.07651294]
training iteration value 0.8622304612450216
